### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by alexxx55555** [peetrike/scripts#2]
Hi,

Can you please create a kb how to use this script? 

thanks

**Comment by peetrike** [comment]
Basically you create a config file and then run script (as described in examples). 

The sample config script is included [here](https://github.com/peetrike/scripts/blob/master/Send-PasswordNotification/Send-PasswordNotification.config) and in Notes section of comment-based-help.

Let me know, if that isn't enough

**Comment by peetrike** [comment]
also added [ReadMe ](https://github.com/peetrike/scripts/blob/master/Send-PasswordNotification/README.md)document to repository
